"""
Reusable HTML components for AlphaLens reports.
"""

from __future__ import annotations

from typing import Any

from app.reporting.formatters import format_metric


def build_header(title: str, subtitle: str = "") -> str:
    """
    Build the report header.
    """

    subtitle_html = ""

    if subtitle:
        subtitle_html = f"<p>{subtitle}</p>"

    return f"""
    <header class="report-header">
        <h1>{title}</h1>
        {subtitle_html}
    </header>
    """


def build_footer() -> str:
    """
    Build the report footer.
    """

    return """
    <footer class="report-footer">
        Generated by <strong>AlphaLens</strong>
    </footer>
    """


def build_kpi_card(label: str, value: Any) -> str:
    """
    Build a KPI card.
    """

    return f"""
    <div class="kpi">
        <div class="kpi-value">
            {value}
        </div>

        <div class="kpi-label">
            {label}
        </div>
    </div>
    """


def build_kpi_grid(cards: list[tuple[str, Any]]) -> str:
    """
    Build KPI grid.
    """

    html = '<div class="kpi-grid">'

    for label, value in cards:
        html += build_kpi_card(label, value)

    html += "</div>"

    return html


def build_metric_row(name: str, value: Any) -> str:
    """
    Build a metric row.
    """

    return f"""
    <div class="metric-row">
        <span>{name}</span>
        <strong>{format_metric(name, value)}</strong>
    </div>
    """


def build_metric_card(title: str, metrics: dict[str, Any]) -> str:
    """
    Build a metric card.
    """

    rows = ""

    for name, value in metrics.items():
        rows += build_metric_row(name, value)

    return f"""
    <div class="section">

        <h2>{title}</h2>

        {rows}

    </div>
    """


def build_dataset_card(dataset_type: str, observations: int) -> str:
    """
    Build dataset information card.
    """

    return build_metric_card(
        "Dataset",
        {
            "Dataset Type": dataset_type.title(),
            "Observations": observations,
        },
    )


def build_metric_grid(cards: list[str]) -> str:
    """
    Build metric grid.
    """

    html = '<div class="grid">'

    for card in cards:
        html += card

    html += "</div>"

    return html


def build_chart_card(title: str, chart_html: str) -> str:
    """
    Wrap embedded chart.
    """

    return f"""
    <div class="section">

        <h2>{title}</h2>

        {chart_html}

    </div>
    """